/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAO;
import controller.GameOption;
import controller.Play_Game;
import controller.XuLyData;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Infomation;

/**
 *
 * @author ADMIN
 */
public class GAME_MAIN extends javax.swing.JFrame {
    Play_Game game;
    GameOption gameOption;
    XuLyData phatAm;
    Infomation s;
    int length;
    public static int muc,mucHoTro;
    
    /**
     * Creates new form GAME_MAIN
     */
    public GAME_MAIN() {
        initComponents();
        textGoiY.setEditable(false);
        textHashTag.setEditable(false);
        textPhienAm.setEditable(false);
        textTime.setEditable(false);
        textNghia.setEditable(false);
        muc=0;
        game=new Play_Game();
        //game.PlayGame(tuKiemTra);
        gameOption=new GameOption();
        phatAm=new XuLyData();
        Image.setIcon(null);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tuKiemTra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        btnkq = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnPhatAm = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        textNghia = new javax.swing.JTextField();
        textPhienAm = new javax.swing.JTextField();
        textHashTag = new javax.swing.JTextField();
        textTime = new javax.swing.JTextField();
        Image = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textGoiY = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        Muc1 = new javax.swing.JMenuItem();
        Muc2 = new javax.swing.JMenuItem();
        Muc3 = new javax.swing.JMenuItem();
        Muc4 = new javax.swing.JMenuItem();
        Muc5 = new javax.swing.JMenuItem();
        Muc6 = new javax.swing.JMenuItem();
        Muc7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Muchotro1 = new javax.swing.JMenuItem();
        Muchotro2 = new javax.swing.JMenuItem();
        Muchotro3 = new javax.swing.JMenuItem();
        Muchotro4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("SELEC 1");

        jMenu3.setText("jMenu3");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));

        tuKiemTra.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        tuKiemTra.setForeground(new java.awt.Color(255, 51, 0));
        tuKiemTra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("TỪ/CỤM TỪ           :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("ĐÁP ÁN CỦA BẠN:");

        textUser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnkq.setBackground(new java.awt.Color(255, 255, 0));
        btnkq.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnkq.setForeground(new java.awt.Color(255, 0, 0));
        btnkq.setText("KIỂM TRA KẾT QUẢ");
        btnkq.setActionCommand("KIỂM TRA ");
        btnkq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkqActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("LET'S PLAY");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("GỢI Ý");

        jButton2.setText("NGHĨA");

        jButton3.setText("PHIÊN ÂM");

        btnPhatAm.setForeground(new java.awt.Color(204, 0, 204));
        btnPhatAm.setText("NGHE PHÁT ÂM");
        btnPhatAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhatAmActionPerformed(evt);
            }
        });

        jButton6.setText("HASHTAG");

        jButton7.setText("THỜI GIAN THÊM");

        jButton8.setText("HÌNH ẢNH MINH HỌA");

        textNghia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textPhienAm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textHashTag.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 0, 0));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setText("GỢI Ý");

        textGoiY.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(790, 790, 790)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jButton8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(btnPhatAm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(419, 419, 419))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(tuKiemTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnkq, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textHashTag, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(textTime, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(textNghia, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(textPhienAm, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(textGoiY))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(textHashTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tuKiemTra, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)
                                    .addComponent(textNghia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textPhienAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3))))))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkq, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(textGoiY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnPhatAm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem4.setText("Chọn lại chế độ chơi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Quay lại giao diện chính");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Option");

        jMenu5.setText("Mức khó");

        Muc1.setText("Mức 1");
        Muc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc1ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc1);

        Muc2.setText("Mức 2");
        Muc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc2ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc2);

        Muc3.setText("Mức 3");
        Muc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc3ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc3);

        Muc4.setText("Mức 4");
        Muc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc4ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc4);

        Muc5.setText("Mức 5");
        Muc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc5ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc5);

        Muc6.setText("Mức 6");
        Muc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc6ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc6);

        Muc7.setText("Mức 7");
        Muc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muc7ActionPerformed(evt);
            }
        });
        jMenu5.add(Muc7);

        jMenu2.add(jMenu5);

        jMenu4.setText("Mức hỗ trợ");

        Muchotro1.setText("Mức 1");
        Muchotro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muchotro1ActionPerformed(evt);
            }
        });
        jMenu4.add(Muchotro1);

        Muchotro2.setText("Mức 2");
        Muchotro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muchotro2ActionPerformed(evt);
            }
        });
        jMenu4.add(Muchotro2);

        Muchotro3.setText("Mức 3");
        Muchotro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muchotro3ActionPerformed(evt);
            }
        });
        jMenu4.add(Muchotro3);

        Muchotro4.setText("Mức 4");
        Muchotro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muchotro4ActionPerformed(evt);
            }
        });
        jMenu4.add(Muchotro4);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Play_Game.danhSach.clear();
        setVisible(false);
        Game a= new Game();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       Play_Game.danhSach.clear();
        setVisible(false);
        Main_View a=new Main_View();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnkqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkqActionPerformed
        // TODO add your handling code here:
       int t=0;
       if(game.kiemTraKetQua(textUser)){
           
           label2.setForeground(Color.red);
           label2.setText("Congratulations");
           if(mucHoTro==4){
               s=gameOption.getInfo();
               JOptionPane.showMessageDialog(null, "Chúc mừng bạn,hay nghe lại phát âm và xem phiên âm để ghi nhớ tốt hơn nhé!!!\n"
                       + "Phiên âm:"+s.getPhienAm());
              
              
               phatAm.phatAmTu(s.getLinkToFile());
           
           }
           
           
           
           if((game.danhSach.size()>1) && (Game.selectOption==1||Game.selectOption==2))
              game.PlayGame(tuKiemTra);
           else if(DAO.list.size()>1&& Game.selectOption==3)
               game.PlayGame(tuKiemTra);
           else{
               JOptionPane.showMessageDialog(null, "Danh sách của bạn quá ít từ");
               t=1;
           }
           if(t!=1){
               switch(muc){
                   case 1: s=gameOption.getInfo();
                           if(s==null){
                           JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
                           }else{
                            textNghia.setText(s.getNghia());
                            textPhienAm.setText(s.getPhienAm());
                            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
                            textHashTag.setText(s.getHashTag());
                            textGoiY.setText(s.getGoiY());
                            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
                            btnPhatAm.setEnabled(true);
                           }
                   break;
                   case 2:            
                            s=gameOption.getInfo();
                            if(s==null){
                            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
                            }else{
                            textNghia.setText(s.getNghia());
                            textPhienAm.setText("");
                            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
                            textHashTag.setText(s.getHashTag());
                            textGoiY.setText(s.getGoiY());
                            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
                            btnPhatAm.setEnabled(true);
            
            
                             }
                   break;
                   case 3:
                        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
           textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(true);
            
            
        }
                   break;
                   case 4:
                       s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            
            
        }
                   break;
                   case 5:
                       s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            String name=s.getTu();
            int length=0;
            for (int i = 0; i < name.length(); i++) {
                if(name.charAt(i)!=' ') length+=1;
            }
            tuKiemTra.setText("("+length+")");
            
            
        }
                   break;
                   case 6:
                       s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText("");
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            String name=s.getTu();
            int length=0;
            for (int i = 0; i < name.length(); i++) {
                if(name.charAt(i)!=' ') length+=1;
            }
            tuKiemTra.setText("("+length+")");
            
            
        }
                   break;
                   case 7:
                        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText("");
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
//            String name=s.getTu();
//            int length=0;
//            for (int i = 0; i < name.length(); i++) {
//                if(name.charAt(i)!=' ') length+=1;
//            }
            tuKiemTra.setText("");
            
            
        }
                   break;
                        
           }
           }
           textUser.setText("");
        
       }else{
           String a=Play_Game.nameString;
           int kt=0;
           for (int i=0;i<DAO.list.size() ;i++) {
               if(DAO.list.get(i).getTu().equals(a)){
                   kt=DAO.list.get(i).getTemp();
                   kt+=1;
                   DAO.list.get(i).setTemp(kt++);
                   break;
               }
           }
           JOptionPane.showMessageDialog(null,"Vui lòng điền lại");
          
           if((mucHoTro==1||mucHoTro==2)&&(muc==5||muc==6)){
               String kqSting=game.hoTro(Play_Game.nameString, textUser.getText());
               textUser.setText(kqSting);
           }else if(mucHoTro==1&&(muc==7||muc<5)){
               String name=s.getTu();
            length=0;
            for (int i = 0; i < name.length(); i++) {
                if(name.charAt(i)!=' ') length+=1;
            }
            textUser.setText("("+length+")");
           }else if(mucHoTro==2&&(muc==7||muc<5)){
               String kqString=game.LCS(Play_Game.nameString, textUser.getText());
               textUser.setText(kqString);
               
               
           }else if(mucHoTro==3){
               btnPhatAm.setEnabled(true);
               JOptionPane.showMessageDialog(rootPane, "Nghe phát âm và đoán lại nhé!!!");
           }
           
           label2.setForeground(Color.black);
           label2.setText("Fail");
           
       }
       
    }//GEN-LAST:event_btnkqActionPerformed

    private void Muc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc1ActionPerformed
        // TODO add your handling code here:
        textUser.setText("");
         muc=1;
         game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);

         s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText(s.getPhienAm());
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText(s.getGoiY());
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(true);
            
            
        }
        
    }//GEN-LAST:event_Muc1ActionPerformed

    private void btnPhatAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhatAmActionPerformed
        // TODO add your handling code here:
        Infomation s=gameOption.getInfo();
        phatAm.phatAmTu(s.getLinkToFile());
        
    }//GEN-LAST:event_btnPhatAmActionPerformed

    private void Muc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc2ActionPerformed
        // TODO add your handling code here:
        textUser.setText("");
        muc=2;
         game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);
         s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText(s.getGoiY());
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(true);
            
            
        }
        
    }//GEN-LAST:event_Muc2ActionPerformed

    private void Muc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc3ActionPerformed
        // TODO add your handling code here:
        textUser.setText("");
        muc =3;
         game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);
        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(true);
            
            
        }
        
    }//GEN-LAST:event_Muc3ActionPerformed

    private void Muc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc4ActionPerformed
        // TODO add your handling code here:
        textUser.setText("");
        muc=4;
         game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);
        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            
            
        }
        
    }//GEN-LAST:event_Muc4ActionPerformed

    private void Muc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc5ActionPerformed
        // TODO add your handling code here
        textUser.setText("");
        muc=5;
        game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);
        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText(s.getNghia());
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            String name=s.getTu();
            length=0;
            for (int i = 0; i < name.length(); i++) {
                if(name.charAt(i)!=' ') length+=1;
            }
            tuKiemTra.setText("("+length+")");
            
            
        }
    }//GEN-LAST:event_Muc5ActionPerformed

    private void Muc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc6ActionPerformed
        // TODO add your handling code here:
        textUser.setText("");
        muc=6;
        game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra);
            
            
         s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText("");
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
            String name=s.getTu();
            length=0;
            for (int i = 0; i < name.length(); i++) {
                if(name.charAt(i)!=' ') length+=1;
            }
            tuKiemTra.setText("("+length+")");
            
            
        }
    }//GEN-LAST:event_Muc6ActionPerformed

    private void Muc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muc7ActionPerformed
        textUser.setText("");
        muc=7;
        game.Play(Game.selectOption, Game.hint);
         game.PlayGame(tuKiemTra); 
        s=gameOption.getInfo();
        if(s==null){
            JOptionPane.showMessageDialog(null, "Không có thông tin từ");
            
        }else{
            textNghia.setText("");
            textPhienAm.setText("");
            textTime.setText("Time:"+s.getTime()+"  Day: "+s.getTempTime());
            textHashTag.setText(s.getHashTag());
            textGoiY.setText("");
            Image.setIcon(new javax.swing.ImageIcon(s.getLinkToImage()));
            btnPhatAm.setEnabled(false);
//            String name=s.getTu();
//            int length=0;
//            for (int i = 0; i < name.length(); i++) {
//                if(name.charAt(i)!=' ') length+=1;
//            }
            tuKiemTra.setText("");
            
            
        }
    }//GEN-LAST:event_Muc7ActionPerformed

    private void Muchotro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muchotro1ActionPerformed
        // TODO add your handling code here:
        mucHoTro=1;
        
    }//GEN-LAST:event_Muchotro1ActionPerformed

    private void Muchotro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muchotro2ActionPerformed
        // TODO add your handling code here:
        mucHoTro=2;
    }//GEN-LAST:event_Muchotro2ActionPerformed

    private void Muchotro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muchotro3ActionPerformed
        // TODO add your handling code here:
        mucHoTro=3;
    }//GEN-LAST:event_Muchotro3ActionPerformed

    private void Muchotro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muchotro4ActionPerformed
        // TODO add your handling code here:
        mucHoTro=4;
    }//GEN-LAST:event_Muchotro4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAME_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAME_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAME_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAME_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GAME_MAIN a= new GAME_MAIN();
               a.setLocationRelativeTo(null);
               a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JMenuItem Muc1;
    private javax.swing.JMenuItem Muc2;
    private javax.swing.JMenuItem Muc3;
    private javax.swing.JMenuItem Muc4;
    private javax.swing.JMenuItem Muc5;
    private javax.swing.JMenuItem Muc6;
    private javax.swing.JMenuItem Muc7;
    private javax.swing.JMenuItem Muchotro1;
    private javax.swing.JMenuItem Muchotro2;
    private javax.swing.JMenuItem Muchotro3;
    private javax.swing.JMenuItem Muchotro4;
    private javax.swing.JButton btnPhatAm;
    private javax.swing.JButton btnkq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField textGoiY;
    private javax.swing.JTextField textHashTag;
    private javax.swing.JTextField textNghia;
    private javax.swing.JTextField textPhienAm;
    private javax.swing.JTextField textTime;
    private javax.swing.JTextField textUser;
    private javax.swing.JLabel tuKiemTra;
    // End of variables declaration//GEN-END:variables
}
